### ISSUE TITLE
homepage image slows site down on mobile and scroll parallax doesnt work on mobile apple devices

### ISSUE THREAD

**Issue by sophiaaaaa** [bit-by-bit-coding/bxb-website#110]
scroll effect doesn't work on ipad or iphone

**Comment by MoralCode** [comment]
Problem 1: the image is HUGE. 4.6-ish megabytes and 2kx2k pixels. should be scaled down to at least biggest size that its ever reasonably shown at. otherwise users are spending time downloading pixels they cant see
![Screenshot_20200916_084410](https://user-images.githubusercontent.com/17362949/93360730-de322600-f7f8-11ea-8bce-10b56f111ebb.png)


Problem 2: found this that might be useful: https://developers.google.com/web/updates/2016/12/performant-parallaxing

**Comment by MoralCode** [comment]
![Screenshot_20200916_091016](https://user-images.githubusercontent.com/17362949/93363721-7e3d7e80-f7fc-11ea-95d9-3c7c5f2d4eff.png)
images scaled down and jpegs optimized according to basically google's recommendations. see linked PR. Also feel free to add the other scroll optimizations to this PR
headshots reduced to a width of 250 (down from ~3000px)
bit by bot images reduced to a width of 500px (down from ~1500px)
recently added logo images reduced down to whatever maximum size they are displayed at on the site (800px wide for the big one, ~25 px tall for the small nav one)

Remember that doubling the width/height of a square image results in a _quadrupling_ of the file size/number of pixels, and thus, the time it takes to download.
