### ISSUE TITLE
Header of about/volunteer page makes page crash sometimes

### ISSUE THREAD

**Issue by Form-And-Function** [bit-by-bit-coding/bxb-website#34]

**Comment by MoralCode** [comment]
judging by the FPS 
![Screenshot_20200622_175630](https://user-images.githubusercontent.com/17362949/85348947-e0af0900-b4b1-11ea-9548-f6f90dace56e.png)

the most likely candidate appears to be the  "non swap sorting visualization" at https://github.com/bit-by-bit-coding/bxb-website/blob/master/scripts/sort.js#L119
its the one that looks like this with the illusion of a bar scrolling from left to right seemingly just reshuffling the tiles:

![Screenshot_20200622_175813](https://user-images.githubusercontent.com/17362949/85349019-28ce2b80-b4b2-11ea-997d-5749e68b976b.png)

i refreshed the page a decent number of times and wasn't able to get Firefox to actually tell me that a script was slowing down a webpage.


That said, here are a few solutions that could help increase page performance:

- rewrite the animations so we can make sure that they are reasonably performant and make sure that less performant algorithms (cough magic sort cough) dont make it onto the site
- find some way to pre-record and just re-play the sequence of tiles. this might reduce the load on peoples computers instead of having to actually sort the cubes every time
- have an option to disable the animations (ideally on by default)
- completely ditch all or most of the header animations (the homepage one is super fun to play with IMO) and design something else with a similar computer-science feel
